### ISSUE TITLE
Как повернуть экран ?

### ISSUE THREAD

**Issue by TechNickEvilCorp** [Sergey1560/fb_st7796s#2]
Комплект оборудования такой же как у вас

сделав всё по инструкции получилось добиться нужного эффекта (но инструкцию я хотел бы переписать для будущих поколений)

Но рядом стоит пятый медведь с точно таким же экраном(не стоковый а заменён с основной) платой всё также работает но нужно повернуть экран
sun50i-h6-st7796s.dts тут меняю строку Rotate и переотправляю + перезагрузка, но нормально работает на значениях 270 и 90 если ставлю 0 или 180 кракозябры на экране и частично картинка остаётся
что ещё нужно сменить чтобы заработало ? с тачем уж как нибудь разберусь наверное
Заранее спасибо

**Comment by Sergey1560** [comment]
Покажите фото экрана, когда стоит вращение на 0 или 180. 
У меня нет этого экрана, поэтому просто проверить у себя не могу.

**Comment by TechNickEvilCorp** [comment]
![IMG_20221008_210149](https://user-images.githubusercontent.com/89976842/194723700-5ed2666f-2d45-4ddb-b528-e895fb138dcd.jpg)
![IMG_20221008_210151](https://user-images.githubusercontent.com/89976842/194723705-87ac7242-4103-4d4c-a442-f03665f4a113.jpg)

![IMG_20221008_210423](https://user-images.githubusercontent.com/89976842/194723715-a484d2e0-0124-4be3-b9e3-ea5cc38e1a0d.jpg)


часть картинки выводится но неправильно и направление как в было выставлено в прошлый раз

**Comment by Sergey1560** [comment]
Если можно, покажите пожалуйста еще вывод dmesg|grep 7796 при ориентации экрана 0 или 180 и при ориентации 90 или 270. Там будет относительно много текста, можно на pastebin.com положить, а сюда ссылку.

**Comment by TechNickEvilCorp** [comment]
> Покажите фото экрана, когда стоит вращение на 0 или 180. У меня нет этого экрана, поэтому просто проверить у себя не могу.

https://pastebin.com/famKm4zG

в последнем тесте ошибся указал 190 но думаю и так понятно

**Comment by TechNickEvilCorp** [comment]
Ещё момент, при старте печати с экрана сам экран побелел до перезагрузки и на второй попытке побелел после печати уже. Известная проблема ?

**Comment by Sergey1560** [comment]
Я возможно исправил проблему с вращением на 0 и 180 градусов. Чтобы проверить, нужно обновить драйвер с github, пересобрать его и заново установить модуль.

**Comment by TechNickEvilCorp** [comment]
![photo_2022-10-11_16-28-51](https://user-images.githubusercontent.com/89976842/195104155-421eb734-fe6a-423c-909f-5bd1b89399c7.jpg)
Теперь всё корректно, спасибо!
![2022-10-11_16-29-47](https://user-images.githubusercontent.com/89976842/195104485-c48db043-a34b-4613-8d5f-cb871ad94058.png)
Добавьте ещё вот тут двоеточие в мануале.
`DISPLAY=:0.0 xinput list-props 'ADS7846 Touchscreen' | grep "Coordinate Transformation Matrix"`
PS. корректная матрица у меня получилась для rotate 0
`DISPLAY=:0.0 xinput --set-prop 'ADS7846 Touchscreen' 'Coordinate Transformation Matrix' 0 -1 1 1 0 0 0 0 1`
