### ISSUE TITLE
Как подключить Orange Pi lite

### ISSUE THREAD

**Issue by lcf2003** [Sergey1560/fb_st7796s#3]
Файл под H3 есть. Но не получается точно определить пины к которым подключать дисплей. Прошу добавить комvентарии, конкретизировать какие пины для Orange Pi Lite

**Comment by Sergey1560** [comment]
На сайте производителя должна быть схема контактов платы и где какая периферия находится. Вам нужен блок SPI (нужны только MOSI, CLK, CS) и любые свободные GPIO ноги для Reset, DC и подсветки.
К драйверу это никакого отношения не имеет, это настраивается в dts.
У меня  такой платы нет и пробовать не на чем.
