### ISSUE TITLE
Запуск драйвера на odroid-c1

### ISSUE THREAD

**Issue by aeremichev** [Sergey1560/fb_st7796s#4]
Можно ли запустить этот драйвер на odroid-c1
https://pi4j.com/1.2/pins/odroid-c1.html

Что для этого нужно?

**Comment by Sergey1560** [comment]
Драйвер не зависит от железа. Если ваш дистрибутив содержит инструменты для сборки (или есть возможность их установить) то не вижу проблем.

**Comment by aeremichev** [comment]
Сергей, спасибо!
Я нашел вариант как заставить работать дисплей с родными драйверами, что есть на odroid-c1.
Может быть кому то будет полезно.
Как основу использовал эту инструкцию. 
https://wiki.odroid.com/legacy/accessory/display/3.2inch_tft_touchscreen_shield/c1/start

Только за место odroidc_tft32  прописал tinylcd35

Так `modprobe fbtft_device name=tinylcd35 rotate=270 gpios=reset:116,dc:115 speed=32000000 cs=0 `

И все сразу заработало.
Дисплей подключал на основе распиновки дисплея https://wiki.odroid.com/accessory/display/3.2inch_tft_touchscreen_shield/spec_pin_info 

Едиственно не с первого раза получилось откалибровать тачскрин, но это может быть мне так повезло. Разрешение тача оказалось больше разрешения дисплея.
Нашел калькулятор на питоне, который уже выдал параметры калибровки которые сработали для меня

`DISPLAY=:0.0 xinput set-prop "ADS7846 Touchscreen" --type=float "Coordinate Transformation Matrix" -2.200104, 0.0, 1.058047, 0.0, 1.292929, -0.045455, 0.0, 0.0, 1.0
`
