### ISSUE TITLE
GPIO orange pi 4 lts

### ISSUE THREAD

**Issue by kiingsyed** [Sergey1560/fb_st7796s#5]
![Rectangle 741](https://user-images.githubusercontent.com/48068361/229642530-c2bd7d51-60cc-4728-9e19-463fbefe96fc.png)
Решил попробовать подключить экран к 4 lts. На первый взгляд отличие от 3 lts в зеркальном отражение пинов, но также напрягает отсутствие MOSI. Насколько в данном случае актуальна схема подключения для 3 lts (В отзеркаленном виде)?

**Comment by Sergey1560** [comment]
MOSI это аббревиатура - Master Out Slave In. На вашей картинке выводы SPI обозначены вместо традиционных MOSI/MISO как TXD и RXD.
